#!/usr/bin/env bash
#MISE description="Compiles for the current OS and architecture"
#MISE sources=["**/*.go", "**/*.gohtml", "static/**/*.css", "go.mod", "go.sum"]
#MISE outputs={auto = true}

set -ex

COMMIT=$(git rev-parse HEAD)
VERSION="$(git describe --tags 2>/dev/null || echo v0.0.0)-dev+$(git rev-parse --short HEAD)"
go build -ldflags "-s -w -X main.Version=$VERSION -X main.Commit=$COMMIT -X main.Date=$(date +%Y-%m-%dT%H:%M:%S%z)" -o build/ ./...
